modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="amputatedragdolls"
version="1.2.0-neoforge-1.21.1"
displayName="Amputated Ragdolls"
logoFile="logo.png"
authors="YMhmD"
description="Keeps amputated limbs on Ragdollified ragdolls and adds GWO gun-shot amputation."

[[mixins]]
config="amputatedragdolls.mixins.json"

[[dependencies.amputatedragdolls]]
modId="neoforge"
type="required"
versionRange="[21.1.251,)"
ordering="NONE"
side="BOTH"

[[dependencies.amputatedragdolls]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.amputatedragdolls]]
modId="mobamputation"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.amputatedragdolls]]
modId="ragdollified"
type="required"
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.amputatedragdolls]]
modId="gwo"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"
